### Rulebooks
GET http://localhost:3000/api/rulebooks
### Rulebook editions
GET http://localhost:3000/api/rulebooks/editions

### Classes
GET http://localhost:3000/api/classes

### Classes with zh
GET http://localhost:3000/api/classes?lang=zh

### Classes + prestige + rulebook filter
GET http://localhost:3000/api/classes?includePrestige=true&rulebookIds=4,6

### Domains
GET http://localhost:3000/api/domains

### Domains with zh
GET http://localhost:3000/api/domains?lang=zh

### Name search
GET http://localhost:3000/api/spells/search?q=fire

### Name search zh
GET http://localhost:3000/api/spells/search?q=火&lang=zh

### Name search + rulebook filter
GET http://localhost:3000/api/spells/search?q=fire&rulebookIds=4,6

### Class + level
GET http://localhost:3000/api/spells/by-level?classIds=1&level=3

### Class + level + lang
GET http://localhost:3000/api/spells/by-level?classIds=1&level=3&lang=zh

### Class + level all + lang
GET http://localhost:3000/api/spells/by-level?classIds=1&level=all&lang=zh

### Spell detail
GET http://localhost:3000/api/spells/42

### Spell batch
POST http://localhost:3000/api/spells/batch
Content-Type: application/json

{
  "ids": [1, 2, 2603, 2612]
}

### Resolve Spell name 
POST http://localhost:3000/api/spells/resolve
Content-Type: application/json

{
  "names": ["Magic Missile", "DefinitelyNotASpell", "Last Breath"],
  "rulebookIds": [6, 56, 86]
}

### meta
GET http://localhost:3000/api/meta?lang=zh
