// Bounded issue561 read-only evidence audit. Not a native QA receipt or writer input.
import {readFileSync,readdirSync,statSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {isDeepStrictEqual as equal} from 'node:util';
import Database from 'better-sqlite3';
import {load} from 'cheerio';
import {localDataDir} from '../../../../../../src/shared/env';
import {loadEnglishRecords,validateSourceCoverage,validateSlicePartition} from '../../../../../../src/dice-intake/qa';
import {parseDiceFile} from '../../../../../../src/dice-intake/parse';
import {reconcile} from '../../../../../../src/dice-intake/reconcile';

const revision=process.argv[2];assert(/^[a-f0-9]{40}$/.test(revision??''),'exact private closeout revision required');
const started=performance.now(),root=localDataDir(),prefix='dice-baselines/issue-520/qa/books/56/closeout/issue-561/',owned=root+'/'+prefix,base=root+'/dice-baselines/issue-520';
const j=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const rows=(p:string)=>readFileSync(p,'utf8').trim().split(/\r?\n/).filter(Boolean).map(l=>JSON.parse(l));
const norm=(s:string)=>s.replace(/\r\n/g,'\n');
const git=(...a:string[])=>execFileSync('git',['-C',root,...a],{maxBuffer:64*1024*1024});
const bind=(path:string,rev:string)=>assert(norm(readFileSync(root+'/'+path,'utf8'))===norm(git('show',rev+':'+path).toString('utf8')),'committed evidence drift '+path);
const folder=(path:string,rev:string)=>{const files=git('ls-tree','-r','--name-only',rev,'--',path).toString('utf8').trim().split('\n');assert(equal(files.map(f=>f.slice(path.length)).sort(),readdirSync(root+'/'+path).sort()),'exact evidence file inventory');for(const f of files)bind(f,rev);};
folder(prefix,revision);
const m=j(owned+'input-manifest.json'),summary=j(owned+'review-summary.json');
assert(m.issue===561&&m.activation===false&&m.nativeMatchedSliceReceipt===false&&m.newNativeAcceptedFields===0);
assert(m.preparedRevision==='6d28f9391273979a35a6bcc86971f0aac5b9f2c8'&&m.sourceRevision==='47a23f9b36b4b827ebf14d7d05f3e564465c6fd5'&&m.mappingRevision===m.sourceRevision);
assert(equal(m.acceptedSiblings.map((s:any)=>[s.issue,s.revision,s.targets]),[[555,'541d3121c60661cca569c5af2bb3b4e3a0264dfe',43],[557,'cf341faed424092642f5e767b53e3237cc8029f3',40],[558,'6bc8ad1f84df3bcc30a7ceaeb45792cd4b5adc11',37]]));
for(const b of m.bindings)bind(b.path,b.revision);
const meta=()=>m.readonly.databases.map((d:any)=>({path:d.path,size:statSync(d.path).size,mtimeMs:statSync(d.path).mtimeMs}));assert(equal(meta(),m.readonly.databases),'DB metadata before');
const r=new Database(m.readonly.databases[0].path,{readonly:true,fileMustExist:true}),c=new Database(m.readonly.databases[1].path,{readonly:true,fileMustExist:true});
r.pragma('query_only=ON');c.pragma('query_only=ON');assert(r.pragma('query_only',{simple:true})===1&&c.pragma('query_only',{simple:true})===1);
const en=loadEnglishRecords(r),books:any[]=r.prepare('SELECT id,name,dnd_edition_id AS editionId FROM dnd_rulebook').all();
const zh:any[]=c.prepare("SELECT spellId,rulebookId,variant,name,descriptionText,descriptionHtml,sourceKey FROM I18nSpellText WHERE lang='zh' ORDER BY spellId,variant").all();
const html=new Map((r.prepare('SELECT id,description_html AS html FROM dnd_spell').all() as any[]).map(t=>[t.id,t.html])),chm=new Map(zh.filter(t=>t.variant==='chm').map(t=>[t.spellId,t]));
const fresh=(t:any,allChinese:boolean)=>{assert(equal(t.english,en.get(t.targetId))&&t.englishHtml===html.get(t.targetId),'current English/HTML/mechanics '+t.targetId);if(allChinese)assert(equal(t.chinese,zh.filter(v=>v.spellId===t.targetId)),'all current Chinese variants '+t.targetId);};
const files=readdirSync(root+'/spells-dice-db-by-mo').filter(n=>n.endsWith('.txt')).sort().map(n=>{const path='spells-dice-db-by-mo/'+n;bind(path,m.sourceRevision);const b=readFileSync(root+'/'+path);return {bytes:b.length,parsed:parseDiceFile(n,b)};});
const candidates=rows(base+'/intake/candidates.jsonl'),inventory=rows(base+'/intake/source-inventory.jsonl');validateSourceCoverage(files,inventory,candidates);
const targets=[...en].map(([id,e])=>({id,rulebookId:e.rulebookId,enName:e.name,zhName:chm.get(id)?.name??null,zhBody:chm.get(id)?.descriptionText??null}));
const replay=reconcile(files.flatMap(f=>f.parsed.records),j(root+'/dice-intake/publication-map.json'),books,targets,m.sourceRevision,j(root+'/chm-mapping/enName-aliases-global.json'));
assert(equal(replay.candidates,candidates)&&equal(replay.targetDispositions,rows(base+'/intake/target-inventory.jsonl'))&&files.length===105&&en.size===5097&&candidates.length===5606,'maintained full input replay');
const ids=[642,657,690,691,692,693,719,730],inputs=rows(owned+'target-inputs.jsonl'),proposals=rows(owned+'proposals.jsonl'),reviews=rows(owned+'reviews.jsonl'),residuals=rows(owned+'residuals.jsonl'),legacy=rows(owned+'legacy-provenance.jsonl'),numeric=rows(owned+'numeric-checks.jsonl'),dispositions=rows(owned+'target-dispositions.jsonl');
assert(equal(m.selection.historicalTargetIds,ids));for(const xs of [inputs,proposals,reviews,legacy])assert(equal(xs.map(t=>t.targetId),ids));for(const t of inputs)fresh(t,true);
const legacyRows=(n:string)=>rows(root+'/dice-qa/books/56/'+n+'.jsonl');
for(const t of legacy){const i=inputs.find(z=>z.targetId===t.targetId),d=legacyRows('decisions').find(z=>z.targetId===t.targetId);assert(equal(t.decision,d)&&equal(t.currentCandidate,candidates.find(z=>z.targetId===t.targetId))&&t.currentCandidate.rulebookId===56&&t.currentCandidate.editionId===5,'authentic original decision/current candidate');assert(t.currentCandidate.sourceKey.split(':').slice(1).join(':')===d.sourceKey.split(':').slice(1).join(':')&&equal(t.currentCandidate.bodyText,d.input.bodyText)&&equal(t.currentCandidate.bodyHtml,d.input.bodyHtml)&&t.currentCandidate.zhName===d.input.zhName,'legacy exact candidate identity/body');assert(d.input.englishName===i.english.name&&d.input.englishDescription===i.english.description&&equal(d.input.englishMechanics,i.english.mechanics),'historical/current English identity');assert(equal(t.corrections,legacyRows('corrections').filter(z=>z.sourceKey===d.sourceKey))&&equal(t.outcome,legacyRows('target-outcomes').find(z=>z.targetId===t.targetId))&&equal(t.fallback,legacyRows('out/fallback').filter(z=>z.targetId===t.targetId))&&equal(t.acceptedFields,legacyRows('out/accepted').filter(z=>z.targetId===t.targetId)),'authentic historical fields/fallback');const a=legacyRows('full-body-audit').find(z=>z.targetId===t.targetId);assert(equal(t.fullBodyAudit,a??null));if(a)assert(a.effectiveText===d.fields.descriptionHtml.replacementText&&a.effectiveText===t.acceptedFields[0].descriptionHtml&&a.englishEvidence.includes(i.english.description),'genuine legacy corrected after');}
const plain=(s:string)=>load(s,null,false).root().text(),nums=(s:string)=>s.replace(/<[^>]*>/g,'').match(/[+-]?\d+(?:d\d+)?(?:\.\d+)?%?/gi)??[],canon=(a:string[])=>a.map(s=>s.replace(/^\+/,'').toLowerCase()).sort();
let segments=0,sentences=0,nIndex=0;const repeated=new Map<string,Set<string>>();
for(let k=0;k<ids.length;k++){const t=inputs[k],p=proposals[k],v=reviews[k];assert(p.rulebookId===56&&p.editionId===5&&p.activation===false&&equal(p.sourceKeys,[])&&p.nativeMatchedSliceReceipt===false&&v.activation===false);assert(v.completeEnglishRead&&v.completeCurrentChineseRead&&v.englishHtmlRead&&v.allMechanicsRead&&v.actualAfterSecondReading&&equal(v.canonicalMechanicsPreserved,t.english.mechanics)&&v.englishBodyPreserved&&v.summaryUntouched&&v.reason.length>100);
 assert(v.name.english===t.english.name&&v.name.after===p.name&&equal(v.name.before,t.chinese.map((z:any)=>z.name)));assert(t.chinese.length?p.name===t.chinese[0].name:legacy[k].acceptedFields.some((z:any)=>z.name===p.name),'honest actual name after');
 const $=load(p.descriptionHtml,null,false);assert($.root().find('p,li,tr').map((_,el)=>$(el).text()).get().join('\n\n')===p.descriptionText,'HTML/text parity');assert($.root().find('*').toArray().every(el=>['p','ul','li','em','a','table','tbody','tr','th','td'].includes(el.tagName)),'bounded HTML tags');
 assert(!/(?:\uFFFD|\u0000|TODO|TBD|placeholder|空白占位|待翻译|\[\[|\|_|\*_)/i.test(p.descriptionHtml),'placeholder/raw residue');assert(!/[A-Za-z]{3,}/.test(p.descriptionText.replaceAll('DC','').replaceAll('XP','').replaceAll('DM','').replaceAll('d10','')),'untranslated alphabetic residue');
 const stack:string[]=[];for(const x of p.descriptionHtml.matchAll(/<(\/)?([a-z]+)(?:\s[^>]*)?>/g)){if(x[1])assert(stack.pop()===x[2]);else stack.push(x[2]);}assert(stack.length===0,'HTML nesting');
 const links=(s:string)=>load(s,null,false)('a').map((_,el)=>load(el).root().children().attr('href')).get();assert(equal(links(t.englishHtml),links(p.descriptionHtml)),'original links preserved');
 let sourceCursor=0,afterCursor=0;for(const b of v.bindings){assert(t.english.description.slice(b.start,b.end)===b.source&&b.start>=sourceCursor&&!t.english.description.slice(sourceCursor,b.start).trim(),'complete source locator');sourceCursor=b.end;const pos=p.descriptionHtml.indexOf(b.afterHtml,afterCursor);assert(pos>=afterCursor&&plain(b.afterHtml)===b.afterText);afterCursor=pos+b.afterHtml.length;assert(b.numericMeaningReviewed&&b.negationTimingScopeBonusMaterialsSavingThrowsAndSrReviewed);assert(b.sentences.map((s:any)=>s.source).join(' ').replace(/\s+/g,' ')===b.source.replace(/\s+/g,' ')&&b.sentences.map((s:any)=>s.afterHtml).join('')===b.afterHtml,'sentence partitions');for(const s of b.sentences){assert(s.reviewed&&plain(s.afterHtml)===s.afterText);if(!repeated.has(s.afterText))repeated.set(s.afterText,new Set());repeated.get(s.afterText)!.add(s.source);sentences++;}
 const n=numeric[nIndex++];assert(n.targetId===p.targetId&&n.segment===b.segment&&equal(n.sourceNumbers,nums(b.source))&&equal(n.afterNumbers,nums(b.afterText))&&n.humanNumericMeaningReviewed);const expected=n.sourceNumbers.slice();if(n.conversion){assert(b.source.includes(n.conversion.sourceNeedle)&&b.afterText.includes(n.conversion.afterNeedle)&&n.conversion.reason.length>20);for(const a of n.conversion.sourceRemove){const q=expected.indexOf(a);assert(q>=0);expected.splice(q,1);}expected.push(...n.conversion.afterAdd);}assert(equal(canon(expected),canon(n.afterNumbers)),'numeric values after explicit conversion '+t.targetId+'/'+b.segment);assert(equal(canon(b.source.match(/\d+d\d+/gi)??[]),canon(b.afterText.match(/\d+d\d+/gi)??[])),'dice parity');segments++;}
 assert(!t.english.description.slice(sourceCursor).trim()&&plain(p.descriptionHtml).replace(/\s+/g,'')===v.bindings.map((b:any)=>b.afterText).join('').replace(/\s+/g,''),'complete available source and actual after');const rs=residuals.filter(z=>z.targetId===p.targetId);assert(v.materialResidualCount===rs.length&&v.availableBodyComplete===rs.every(z=>z.bodyComplete)&&equal(p.residualFields,rs.flatMap(z=>z.fields))&&p.bodyStatus===(v.availableBodyComplete?'complete-available-DB-English':'partial-or-ambiguous-DB-English'));
 assert(equal(v.unpopulatedMechanics,Object.entries(t.english.mechanics).filter(([_,v])=>v===null||v===''||Array.isArray(v)&&!v.length).map(([field,value])=>({field,value}))),'unpopulated mechanics honestly preserved');
}
assert(nIndex===numeric.length&&segments===126&&sentences===127&&numeric.filter(n=>n.conversion).length===5);
const repeats=[...repeated].filter(([_,s])=>s.size>1);assert(repeats.every(([t])=>t.length<45),'long template reuse');
assert(equal(residuals.map(t=>t.targetId),[657,690,692,693,719])&&residuals.every(t=>t.activation===false&&t.ownerIssue===561&&t.reason.length>100&&t.locator&&t.fallback));for(const t of residuals)assert(t.needles.every((n:string)=>inputs.find(z=>z.targetId===t.targetId).english.description.includes(n)));
const currentNames=(lookup:string)=>(r.prepare('SELECT s.id,s.name,s.rulebook_id AS rulebookId,b.dnd_edition_id AS editionId FROM dnd_spell s JOIN dnd_rulebook b ON b.id=s.rulebook_id WHERE lower(s.name)=lower(?) ORDER BY s.rulebook_id,s.id').all(lookup) as any[]).map(t=>({...t,chineseNames:c.prepare("SELECT variant,name,sourceKey FROM I18nSpellText WHERE spellId=? AND lang='zh' ORDER BY variant").all(t.id)}));
const names=j(owned+'reference-name-qa.json');for(const t of names.lookups)assert(equal(t.rows,currentNames(t.lookup)),'current reference name identity');assert(names.inherited.length===1&&names.inherited[0].targetId===2787);for(const t of names.inherited)fresh(t,false);assert(equal(reviews.find(t=>t.targetId===730).inheritedReferenceIds,[2787]));
for(const b of names.externalBindings){const s=reviews.find(t=>t.targetId===b.targetId).bindings[b.segment],n=names.lookups.flatMap((t:any)=>t.rows).find((t:any)=>t.id===b.referenceId);assert(s.source.includes(b.sourcePhrase)&&s.afterText.includes(b.afterName)&&n?.chineseNames.some((t:any)=>t.name===b.afterName),'bound actual reference name');}
const bookIds=[...en].filter(([_,e])=>e.rulebookId===56).map(([id])=>id).sort((a,b)=>a-b);assert(bookIds.length===128&&equal(m.selection.allTargetIds,bookIds)&&equal(dispositions.map(t=>t.targetId),bookIds));
const partitions=[ids];let siblingResiduals=0;const bundles=new Map<number,any>([[561,{inputs,proposals,reviews,residuals,path:prefix,revision:'self-exact-private-revision'}]]);
for(const s of m.acceptedSiblings){folder(s.path,s.revision);const sm=j(root+'/'+s.path+'input-manifest.json');assert(sm.preparedRevision===m.preparedRevision&&sm.sourceRevision===m.sourceRevision&&sm.mappingRevision===m.mappingRevision);const xs=rows(root+'/'+s.path+'target-inputs.jsonl'),ps=rows(root+'/'+s.path+'proposals.jsonl'),vs=rows(root+'/'+s.path+'reviews.jsonl'),rs=rows(root+'/'+s.path+'residuals.jsonl');assert(xs.length===s.targets&&equal(xs.map(t=>t.targetId),sm.selection.targetIds)&&equal(ps.map(t=>t.targetId),sm.selection.targetIds)&&equal(vs.map(t=>t.targetId),sm.selection.targetIds));for(const t of xs){fresh(t,true);assert(t.english.rulebookId===56&&t.english.editionId===5);}for(const t of rows(root+'/'+s.path+'referenced-inputs.jsonl'))fresh(t,false);for(const t of j(root+'/'+s.path+'reference-name-qa.json').lookupNames)assert(equal(t.rows,currentNames(t.lookup)),'sibling reference name current binding');assert(ps.every(t=>t.activation===false&&equal(t.sourceKeys,[])));assert(rs.every(t=>t.ownerIssue===s.issue&&t.activation===false));siblingResiduals+=rs.length;partitions.push(sm.selection.targetIds);bundles.set(s.issue,{inputs:xs,proposals:ps,reviews:vs,residuals:rs,path:s.path,revision:s.revision});}
// Reuse the maintained membership check only. These mixed proposals are not native scopes/receipts.
validateSlicePartition(bookIds,partitions.map(targetIds=>({kind:'slice' as const,rulebookId:56,targetIds,baselineRevision:m.preparedRevision,sourceRevision:m.sourceRevision,mappingRevision:m.mappingRevision})));
for(const d of dispositions){const b=bundles.get(d.ownerIssue);assert(b&&d.activation===false&&d.rulebookId===56&&d.editionId===5&&d.evidencePath===b.path&&d.evidenceRevision===b.revision);const p=b.proposals[d.proposalRecordIndex],i=b.inputs[d.inputRecordIndex],v=b.reviews[d.reviewRecordIndex];assert(p.targetId===d.targetId&&i.targetId===d.targetId&&v.targetId===d.targetId&&d.bodyState===p.bodyStatus&&d.mechanicsState===p.mechanicsStatus&&d.nameState===p.nameReview);const rs=b.residuals.flatMap((t:any,k:number)=>t.targetId===d.targetId?[{ownerIssue:d.ownerIssue,path:b.path+'residuals.jsonl',recordIndex:k,evidenceRevision:b.revision}]:[]);assert(equal(d.residualRefs,rs),'all residual owners/revisions/indices');assert(equal(p.residualFields,rs.flatMap((t:any)=>b.residuals[t.recordIndex].fields))&&v.materialResidualCount===rs.length);}
assert(siblingResiduals===21&&summary.targets===128&&summary.siblingTargets===120&&summary.historicalTargets===8&&summary.historicalEnglishCharacters===11295&&summary.inheritedEnglishCharacters===3043&&summary.fullyReviewedWithoutMaterialResidual===102&&summary.targetsWithResidual===26&&summary.residualRecords===26&&summary.currentBodyCompleteTargets===111&&summary.activation===false&&summary.nativeMatchedSliceReceipt===false&&summary.globalDiceQaComplete===false);
r.close();c.close();assert(equal(meta(),m.readonly.databases),'DB metadata unchanged');
const bytes=(p:string):number=>readdirSync(p,{withFileTypes:true}).reduce((n,f)=>n+(f.isDirectory()?bytes(p+'/'+f.name):statSync(p+'/'+f.name).size),0);
assert(bytes(owned)<5*1024*1024&&process.resourceUsage().maxRSS<512*1024,'resource budget');
console.log(JSON.stringify({status:'PASS',revision,targets:128,exactPartitions:[43,40,37,8],historicalSegments:segments,historicalSentenceGroups:sentences,siblingResiduals,historicalResiduals:5,noMaterialResidual:102,targetsWithResidual:26,bodyComplete:111,nativeMatchedSliceReceipt:false,activation:false,readonly:true,elapsedSeconds:(performance.now()-started)/1000,maxRssKiB:process.resourceUsage().maxRSS,privateBytes:bytes(owned),repeatedShortGroups:repeats.length}));
