// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma-rules-clean/schema.prisma",
  migrations: {
    path: "prisma-rules-clean/migrations",
  },
  datasource: {
    url: process.env["RULES_CLEAN_DATABASE_URL"] as string,
  },
});
