import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { englishActions, inspectActions, kinds } from "./actions";
import { scan, frequency, actionInventory, main, selectChinese, selectSample, outputDirectory, type TextRow } from "./cli";
import { actionFrequency } from "./frequency";

const check = (en: string, zh: string | null, header: string | null = null) => inspectActions(en, header, zh);
assert.equal(check("You activate this as an immediate action.", "你激活此效果。")[0]!.status, "candidate");
for (const synonym of ["直觉", "即时", "瞬间"]) {
  assert.equal(check("You activate this as an immediate action.", `你以${synonym}动作激活此效果。`)[0]!.reason, "lexical-support-context-unverified");
}
assert.equal(check("You activate this as an immediate action.", "你以迅捷动作激活此效果。")[0]!.status, "candidate");
assert.equal(check("You end this as a swift action.", "施法时间：迅捷动作\n你结束此效果。")[0]!.status, "candidate");
const martial = check("Activate as an immediate action.", "发动时间：直觉动作\n激活此效果。", "1 immediate action");
assert.equal(martial[0]!.chineseOccurrences, 1);
assert.equal(martial[1]!.status, "candidate");
const counts = actionFrequency([1,2,3].map(spellId => ({spellId, english: "A free action. A free action.", castingTime: "1 free action", chinese: "发动时间：自由动作\n一个自由动作和一个自由动作。特殊动作。"})));
assert.equal(counts.english.find(r=>r.phrase === "body:free")!.documentFrequency, 3);
assert.equal(counts.english.find(r=>r.phrase === "body:free")!.occurrences, 6);
assert.equal(counts.english.find(r=>r.phrase === "body:free")!.concordance.length, 2);
assert.equal(counts.chineseLabels.find(r=>r.phrase === "casting-time:自由动作")!.documentFrequency, 3);
assert.deepEqual(counts.chineseSuffixCandidates.map(r=>r.phrase), ["body:特殊动作"]);
const unrelated = check("You activate this as a swift action.\nYou end it as a swift action.", "你以迅捷动作激活。\n你结束效果。");
assert(unrelated.every(row => row.status === "candidate" && row.reason === "action-count-deficit"));
assert.equal(check("You end this as a swift action.", "你结束效果。\n另一个能力以迅捷动作激活。")[0]!.status, "unknown");
assert.equal(check("You maintain this as a move action.", "你以移动动作维持。")[0]!.role, "sustain");
assert.equal(check("You end this as a free action.", "你以自由动作结束。")[0]!.role, "end");
assert.deepEqual(englishActions("No action is required. A move-equivalent action, two full round actions, a standard action, a swift action, an immediate action and a free action." ).map(r=>r.kind).sort(), [...kinds].sort());
assert.equal(check("This does not require an action.", "这不需要动作。")[0]!.chineseOccurrences, 1);
for (const phrase of ["no action", "no actions", "no other action", "no other actions"]) {
  const en = `At dawn, the guard can take ${phrase} until sunset.`;
  const [finding] = check(en, "守卫静止不动。");
  assert.equal(finding!.kind, "no-action");
  assert.equal(finding!.offset, en.indexOf(phrase));
  assert.equal(finding!.context, en);
  assert.equal(finding!.role, "other");
  assert.equal(finding!.status, "unknown");
  assert.equal(finding!.reason, "action-prohibition-context-unverified");
}
for (const negative of ["cannot", "can't", "can’t", "can not"]) {
  const en = `First line.\r\nAfter arriving, you ${negative} take any other actions this round.`;
  const [finding] = check(en, "抵达后你无法进行其他行动。");
  assert.equal(finding!.line, 1);
  assert.equal(finding!.offset, en.split("\r\n")[1]!.indexOf(negative));
  assert.equal(finding!.status, "unknown");
  assert.equal(finding!.expectedOccurrences, 1);
}
assert.equal(englishActions("You take actions. You take other actions. An action is available.").length, 0);
assert.equal(check("No actions are required to end the glow.", "结束光芒无需动作。")[0]!.role, "end");
for (const raw of ["1 action", "One action", "  ONE action  "]) {
  const findings = check("Use a move action to sustain the glow.", "施法时间：标准动作\n以移动动作维持光芒。", raw);
  const header = findings[0]!;
  assert.equal(header.kind, "unknown");
  assert.equal(header.field, "casting-time");
  assert.equal(header.context, raw);
  assert.equal(header.offset, raw.search(/\S/u));
  assert.equal(header.status, "unknown");
  assert.equal(header.reason, "English-action-family-unresolved");
  assert.equal(header.expectedOccurrences, 1);
  assert.equal(header.chineseOccurrences, 0);
  assert.deepEqual(header.chineseEvidence, []);
  assert.equal(findings[1]!.kind, "move");
  assert.equal(findings[1]!.field, "body");
  assert.equal(findings[1]!.role, "sustain");
  assert.equal(englishActions(raw).length, 0);
}
for (const raw of ["2 actions", "One action to activate", "Some action", "1 action/round"]) {
  assert.equal(check("", "施法时间：标准动作", raw).length, 0);
}
for (const kind of kinds.filter(kind => kind !== "no-action")) {
  assert.equal(check("", "", `1 ${kind} action`)[0]!.kind, kind);
}
assert.equal(check("", "普通文本。", "1 action")[0]!.reason, "English-action-family-unresolved");
assert.equal(check("", null, "One action")[0]!.reason, "missing-selected-Chinese");
const genericFrequency = actionFrequency([{spellId: 1, english: "One action", castingTime: "1 action", chinese: "施法时间：标准动作"}]);
assert.deepEqual(genericFrequency.english.map(row => row.phrase), ["casting-time:unknown"]);
assert.equal(check("You use a standard action.", "")[0]!.reason, "missing-selected-Chinese");
assert.equal(check("No mechanical action phrase.", "普通文本。").length, 0);
assert.equal(check("You activate this as an immediate action.", "你以直觉动作激活。", "1 standard action")[0]!.field, "casting-time");
assert.deepEqual(englishActions("Actions other than free, swift, or immediate actions trigger damage.").map(r=>r.kind), ["free", "swift", "immediate"]);
assert(check("Actions other than free, swift, or immediate actions trigger damage.", "除了自由，直觉，迅捷以外的动作触发伤害。").every(r=>r.status === "unknown"));
assert.equal(check("Activate as a swift action.", "This activates as a swift action.")[0]!.status, "candidate");
assert.equal(check("Activate as a swift action.", "Activate as a swift action.")[0]!.reason, "selected-English-fallback");
assert.equal(check("Activate as a swift action.", "以迅捷动作激活。", "standard action")[0]!.reason, "Chinese-casting-header-unavailable");
const emptyEffective: TextRow = { variant: "effective", rulebookId: 1, name: null, descriptionText: null, sourceKey: null, nameProvenanceJson: null, bodyProvenanceJson: null };
const chm = { ...emptyEffective, variant: "chm", descriptionText: "迅捷动作" };
assert.equal(selectChinese([chm, emptyEffective]), emptyEffective);
assert.equal(selectChinese([chm]), chm);
assert.equal(selectChinese([emptyEffective, chm], "chm"), chm);
assert.throws(() => outputDirectory(path.join(os.tmpdir(), "public-action-qa")), /private|Output/);
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "action-qa-"));
const dataRootBefore = process.env.DATA_REPO_PATH;
try {
  process.env.DATA_REPO_PATH = dir;
  const termRoot = path.join(dir, "term-qa");
  const fresh = path.join(termRoot, "issue-999", "fresh");
  assert.equal(outputDirectory(fresh), fresh);
  assert.throws(() => outputDirectory(termRoot), /new child/);
  assert.throws(() => outputDirectory(path.join(termRoot, "..", "outside")), /new child/);
  fs.mkdirSync(fresh, { recursive: true });
  assert.throws(() => outputDirectory(fresh), /already exists/);
  const file = path.join(dir, "content.sqlite"); const db = new Database(file);
  db.exec(`CREATE TABLE SpellContent (legacySpellId INTEGER, sourceRulebookId INTEGER, canonicalName TEXT, descriptionText TEXT, castingTimeRaw TEXT);
    CREATE TABLE I18nSpellText (spellId INTEGER,rulebookId INTEGER,lang TEXT,variant TEXT,name TEXT,descriptionText TEXT,sourceKey TEXT,nameProvenanceJson TEXT,bodyProvenanceJson TEXT);
    INSERT INTO SpellContent VALUES (876,58,'Synthetic anchor','Activate as an immediate action.','1 standard action');
    INSERT INTO I18nSpellText VALUES (876,58,'zh','chm','旧','施法时间：标准动作\n激活效果。','legacy',NULL,NULL);
    INSERT INTO I18nSpellText VALUES (876,58,'zh','effective','当前','施法时间：标准动作\n以直觉动作激活。',NULL,'{}','{"origin":"synthetic"}');`);
  db.close(); const before = fs.readFileSync(file); const result = scan(file, [876]);
  assert.equal(result[0]!.selected!.variant, "effective");
  assert.equal(result[0]!.selected!.bodyProvenanceJson, '{"origin":"synthetic"}');
  assert.equal(result[0]!.findings.find(f=>f.field === "body")!.status, "unknown");
  assert.equal(result[0]!.chmContrast!.findings.find(f=>f.field === "body")!.status, "candidate");
  assert.deepEqual(fs.readFileSync(file), before);
  const genericSeed = new Database(file);
  genericSeed.exec("INSERT INTO SpellContent VALUES (877,86,'Synthetic generic header','Ordinary text.','One action')");
  genericSeed.exec("INSERT INTO I18nSpellText VALUES (877,86,'zh','chm','Old','施法时间：标准动作',NULL,NULL,NULL)");
  genericSeed.exec("INSERT INTO I18nSpellText VALUES (877,86,'zh','effective','Empty',NULL,NULL,NULL,NULL)");
  genericSeed.close();
  const genericBefore = fs.readFileSync(file), genericInventory = actionInventory(file).find(row => row.spellId === 877)!;
  assert.equal(genericInventory.selectedVariant, "effective");
  assert.equal(genericInventory.languageStatus, "missing-Chinese");
  assert.equal(genericInventory.scReadonly, true);
  assert.equal(genericInventory.findings[0]!.kind, "unknown");
  assert.equal(genericInventory.findings[0]!.status, "unknown");
  assert.equal(genericInventory.findings[0]!.reason, "missing-selected-Chinese");
  assert.deepEqual(fs.readFileSync(file), genericBefore);
  const removeGeneric = new Database(file);
  removeGeneric.exec("DELETE FROM SpellContent WHERE legacySpellId=877; DELETE FROM I18nSpellText WHERE spellId=877");
  removeGeneric.close();
  assert.equal(frequency(file).chineseLabels.some(row=>row.phrase === "body:直觉动作"), true);
  const seed = new Database(file);
  const insert = seed.prepare("INSERT INTO SpellContent VALUES (?,1,'Synthetic chunk','Use a move action to sustain.','1 standard action')");
  for (let id=1;id<=205;id++) insert.run(id);
  seed.prepare("INSERT INTO I18nSpellText VALUES (100,1,'zh','chm','old','以移动动作维持。',NULL,NULL,NULL)").run();
  seed.prepare("INSERT INTO I18nSpellText VALUES (100,1,'zh','effective','empty',NULL,NULL,NULL,NULL)").run();
  seed.close();
  const inventoryBefore = fs.readFileSync(file), all = actionInventory(file);
  assert.equal(all.length, 206); assert.equal(new Set(all.map(row=>row.spellId)).size, 206);
  assert.deepEqual(all.map(row=>row.spellId), [...Array.from({length:205},(_,i)=>i+1),876]);
  assert.equal(all.find(row=>row.spellId===100)!.selectedVariant, "effective");
  assert.equal(all.find(row=>row.spellId===100)!.languageStatus, "missing-Chinese");
  assert.equal(all.find(row=>row.spellId===101)!.selectedVariant, null);
  assert(all.find(row=>row.spellId===101)!.findings.every(f=>f.status==="unknown"));
  assert.equal(all.find(row=>row.spellId===876)!.findings.find(f=>f.field==="body")!.status,"unknown");
  assert.deepEqual(fs.readFileSync(file), inventoryBefore);
  assert.throws(()=>main(["--content-db",file,"--out",path.join(termRoot,"bad"),"--inventory","--sample","1"]),/no sample/);
  const fullOut = path.join(termRoot,"full-inventory");
  main(["--content-db",file,"--out",fullOut,"--inventory","--frequency"]);
  assert.deepEqual(fs.readFileSync(path.join(fullOut,"inventory.jsonl"),"utf8").trim().split("\n").map(line=>JSON.parse(line)),all);
  assert.equal(JSON.parse(fs.readFileSync(path.join(fullOut,"report.json"),"utf8")).inventoryEntries,206);
  assert.equal(fs.existsSync(path.join(fullOut,"frequency.json")),true);
  assert.throws(()=>main(["--content-db",file,"--out",fullOut,"--inventory"]),/already exists/);
  assert.deepEqual(fs.readFileSync(file), inventoryBefore);
  // A canonical duplicate must fail rather than silently deduplicate.
  const duplicate = new Database(file);
  duplicate.exec("INSERT INTO SpellContent SELECT * FROM SpellContent WHERE legacySpellId=205"); duplicate.close();
  assert.throws(()=>actionInventory(file),/Duplicate canonical/);
  const removeDuplicate = new Database(file);
  removeDuplicate.exec("DELETE FROM SpellContent WHERE rowid=(SELECT MAX(rowid) FROM SpellContent WHERE legacySpellId=205)"); removeDuplicate.close();
  assert.throws(() => scan(file, [999]), /Unknown stable ID/);
  const update = new Database(file);
  update.prepare("UPDATE I18nSpellText SET rulebookId = 99 WHERE variant = 'effective'").run();
  update.close();
  assert(scan(file,[876])[0]!.findings.every(f=>f.reason === "selected-book-mismatch" && f.status === "unknown"));
  const fallback = new Database(file);
  fallback.prepare("UPDATE I18nSpellText SET rulebookId=58, bodyProvenanceJson=? WHERE variant='effective'").run(JSON.stringify({targetId:876,field:"body",language:"en"}));
  fallback.close();
  assert(scan(file,[876])[0]!.findings.every(f=>f.reason === "provenance-English-fallback" && f.status === "unknown"));
  const empty = new Database(file);
  empty.prepare("UPDATE I18nSpellText SET descriptionText=NULL WHERE variant='effective'").run();
  empty.close();
  assert.equal(frequency(file).chineseLabels.length, 0);
  assert.deepEqual(selectSample([{spellId:876,book:58,name:"anchor",english:"",castingTime:null}],100), [876]);
} finally {
  if (dataRootBefore === undefined) delete process.env.DATA_REPO_PATH;
  else process.env.DATA_REPO_PATH = dataRootBefore;
  fs.rmSync(dir, { recursive: true, force: true });
}
console.log("Action QA portable regressions passed (omission, scope/count, synonyms, uncertainty, variant, provenance, readonly DB)");
